### ISSUE TITLE
Hash functions do not generate uniform distribution over filter indexes.

### ISSUE THREAD

**Issue by rot256** [ayazhafiz/xorf#16]
First, thanks for writing and maintaining the xorf crate!

The number of zero entries in the filter appears to be significantly higher at the end / start of the filter.Exhibit the plot below, generated for a 15MB Fuse16 filter (~7,000,000 entries):

![Figure_1](https://user-images.githubusercontent.com/7559534/82349267-30ee0380-99fa-11ea-98bb-e6e7bb1bf51b.png)

This plot shows the number of zero entries within a 2000 element sliding window sampled over the filter. Since universal hash functions are used to determine the 3 indexes assigned to each element I would expect the rate of zeroes to be roughly constant over the filter. However the rate is much higher at the low indexes and the high indexes.

The keys (64-bit integers) used to generate the filter are uniformly random.

**Side note:** It might not be optimal to set "unused entries" to zero, since we would thus expect a disproportional number of element to be zero: 1-in-10 elements as a result of the under-utilization required to generate a filter successfully. Hence any element x with fingerprint(x) = 0 satisfies fingerprint(x) = B[h1(x)] ^ B[h2(x)] ^ B[h3(x)] with probability > 1/1000, where as this is the case with probability < 1/65000 otherwise. This increases the false positive rate. Setting unused elements (after generation) to random values should eliminate this abnormality.

**Comment by ayazhafiz** [comment]
Thanks for the report.

I wonder if the same thing will be observed for the `Xor8`/`Xor16` implementations. My guess is yes, since fuse graphs are supposed to be uniform as well, but this is something we should look into.

Setting unused elements to random values sounds reasonable to me. Feel free to submit a PR if you would like. I will investigate on the above.

**Comment by rot256** [comment]
This is the plot for Xor16. 

![Figure_2](https://user-images.githubusercontent.com/7559534/82436768-a1e2f900-9a96-11ea-824e-b0dbbeab6a25.png)


Since generation attempts first attempts to set something in the first [0,.. |B|/3) range (first hash function), if not possible then set something in the [|B|/3, ... |B|2/3] range (second hash function) and lastly fall back to the [|B|2/3, |B|) range.

For reference here is the code to generate the samples:

```rust
use rand::Rng;
use xorf::{Filter, Xor16};
use core::convert::TryFrom;

fn main() {
    let mut keys: Vec<u64> = Vec::with_capacity(7_000_000);

    for i in 0..7_000_000 {
        let key: u64 = rand::thread_rng().gen();
        keys.push(key);
    }

    let filter = Xor16::try_from(keys).unwrap();

    let window_size = 2000;
    let mut zeroes: usize = 0;
    // modified to expose the fingerprint array
    let fp = filter.fingerprints();
    for (i, t) in fp.iter().enumerate() {
        if *t == 0 {
            zeroes += 1;
        }
        if i > window_size && fp[i-window_size] == 0 {
            zeroes -= 1;
        }
        if i > window_size && i % 333 == 0 {
            println!("{}", zeroes);
        }
    }
}
```

And the code used for plotting:

```python
import matplotlib.pyplot as plt

with open('zeroes.txt', 'r') as f:
    x = [int(v) for v in f.readlines()]

plt.xlabel('Sample')
plt.ylabel('Zeroes in 2000 element window')
plt.plot(x)
plt.show()
```

> Setting unused elements to random values sounds reasonable to me. Feel free to submit a PR if you would like. 

I will see if I can cook something up.

**Comment by ayazhafiz** [comment]
Wow, that is really interesting. I can't think of a good explanation at the moment; apologies for not having much time to investigate this yet. The original authors of this algorithm (Thomas Mueller Graf and Daniel Lemire) may be interested in this as well, or have some insight...
