### ISSUE TITLE
Is there a way to tune the false positive rate to reduce space?

### ISSUE THREAD

**Issue by vlovich** [ayazhafiz/xorf#61]
The bloom filter is nice because I can [tune it](https://docs.rs/bloom/latest/bloom/bloom/struct.BloomFilter.html) to whatever false positive rate and number of keys I want. Is it possible to provide a similar mechanism to a generic BinaryFuse filter so that it takes up whatever size/space tradeoff I need? I don't see anything in the filter about hard-coded bits/entry so I'm wondering if this is a design choice or if I'm missing something.

**Comment by ayazhafiz** [comment]
Hi, sorry for the very late response. Unfortunately, these filters are not really designed to tradeoff size and space as far as I know - they try to optimize for both and have a tight asymptotic as a result. It may be helpful to get in direct correspondence with the authors of the Xor filter, (Thomas Mueller Graf and/or Daniel Lemire), who may have some suggestions. My understanding of their paper is that this is not directly extendable, though.
