### ISSUE TITLE
Cap total number of bits

### ISSUE THREAD

**Issue by ozgrakkurt** [ayazhafiz/xorf#69]
is it possible to limit total number of bits in the filter?

**Comment by ayazhafiz** [comment]
Do you mean the total number of items in the filter, or the bits reserved
per item?

If you mean the latter, no, there is no way to decrease the amount of space
used per item. If you are using the BinaryFuse filters, they
typically contain ~12% space overhead on top of the size of the elements
you insert into the filter.

You can always decrease the number of items you insert into the filter, but
that is something you would have to determine yourself.

**Comment by ozgrakkurt** [comment]
thank you for info!
