### ISSUE TITLE
is it possible to serialize filters to disk?

### ISSUE THREAD

**Issue by shi-yan** [ayazhafiz/xorf#78]
I hope to use this library as an optimization for my backend. Constructing filters online can be costly, hence I hope to serialize the filters onto the disk.

Can I do this? especially I want to serialize a HashProxy struct onto the disk. 

My use case:

I want to build an end-to-end encrypted group messaging system. When a user requests a message, the server needs to quickly figure out if the user has the permission to access the message (if the person belongs to this group.).

For each messaging group, once it is formed, I want to generated a filter and cache it in my db. When a request comes in, I pull this cached filter to filter out unauthorized users, and for missed unauthorized users, I will do a secondary filtering by checking the group manifest.

**Comment by ayazhafiz** [comment]
`HashProxy` supports serialization with both `serde` and `bincode` via the "serde" and "bincode" features, respectively. Does that satisfy your needs?

**Comment by shi-yan** [comment]
Thank you so much! I didn't find the api in the document, but after looking at the code I was able to get serialization working. 

Yes, bincode serialization satisfy my needs!
