### ISSUE TITLE
32-bit filters

### ISSUE THREAD

**Issue by ayazhafiz** [ayazhafiz/xorf#8]
We can trivially add support for 32-bit filters by altering parameters of construction for the existing 8 and 16 bit filters.

**Comment by stiiifff** [comment]
@ayazhafiz I have a draft PR coming up. But I'm seeing an improbably 0.0% false positive rate on 1M and even 10M-20M sample sizes. Don't know if you'd have an insight on why that could be ? Haven't checked the maths though (it probably flies over my head tbh).

**Comment by ayazhafiz** [comment]
32 bits is quite a lot. in this scheme we would expect the false positive rate to be 1/2^32=~1/(4 billion). At that point, even being able to construct 1B keys would likely become a limiting factor (you would need 32GB of main memory).

**Comment by stiiifff** [comment]
Makes sense, was going through the paper to get the numbers. Let me see if I can test that just for the sake of it.
